# Trainer config
trainer:
  #   (type: int, default: 100_000)
  max_steps: 100_000

  precision: bf16-mixed # Can be bf16-mixed on supported GPUs

  accumulate_grad_batches: 3

  # Run validation every half epoch
  val_check_interval: 0.5

  logger:
  - class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: bart-base
      project: language-diffusion
      log_model: true
      save_dir: logs


# Model configuration
model:

  # Model class path
  class_path: src.model.bart.BartBaseline
  init_args:
    transformer_name: facebook/bart-base
    learning_rate: 5e-07
    weight_decay: 0.01
    exclude_params: ["layer_norm.weight", "bias"]

# Data configuration
data:

  # Data class 
  class_path: src.data.HFDataModule
  init_args:
    tokenizer_name: facebook/bart-base
    batch_size: 4
    num_workers: 4
